controllers/PedidosController.php
<?php

namespace app\controllers;

use app\models\Pedidos;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PedidosController implements the CRUD actions for Pedidos model.
 */
class PedidosController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                // acciones del controlador que voy a gestionar
                // con el control de cuentas de usuario
                'only' => ['*'],
                'rules' => [
                    [
                        //acciones que pueden realizar los usuarios logueados
                        'actions' => [],
                        'allow' => true,
                        'roles' => ['@'], // @ indica  usuario logueado

                    ],
                    [
                        //acciones que pueden realizar los usuarios no logueados
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['?'], // ? indica  usuario no logueado
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pedidos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Pedidos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'idPedido' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pedidos model.
     * @param int $idPedido Id Pedido
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($idPedido)
    {
        return $this->render('view', [
            'model' => $this->findModel($idPedido),
        ]);
    }

    /**
     * Creates a new Pedidos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Pedidos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'idPedido' => $model->idPedido]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pedidos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $idPedido Id Pedido
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($idPedido)
    {
        $model = $this->findModel($idPedido);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'idPedido' => $model->idPedido]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pedidos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $idPedido Id Pedido
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($idPedido)
    {
        $this->findModel($idPedido)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pedidos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $idPedido Id Pedido
     * @return Pedidos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($idPedido)
    {
        if (($model = Pedidos::findOne(['idPedido' => $idPedido])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Clasificacion;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Productos;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionClasificaciones()
    {
        $clasificaciones = Clasificacion::find()->all();

        return $this->render('clasificaciones', [
            'clasificaciones' => $clasificaciones
        ]);
    }

    public function actionProductos($id)
    {
        $datos = Productos::find()->where(['clasificacion' => $id])->all();

        return $this->render("productos", [
            "datos" => $datos,

        ]);
    }

    public function actionVerproducto($idProducto)
    {
        $consulta = Productos::find()->where(['idProducto' => $idProducto]);

        $dato = $consulta->one();

        return $this->render('verproducto', [
            'dato' => $dato,
        ]);
    }
}

views/site/_productos.php
<?php

use yii\helpers\Html;

?>

<div class="producto">

    <h3><?= $dato['nombre'] ?></h3>


    <p><?= $dato['precio'] ?> €</p>

    <p>
        <?php
        if (isset($dato['foto'])) {
            echo Html::img("@web/imgs/productos/{$dato['foto']}", ['style' => 'width:200px;height: 200px', 'class' => 'img-thumbnail']);
        } else {
            echo  Html::img("@web/imgs/notfound.png", ['style' => 'width:200px;height: 200px', 'class' => 'img-thumbnail']);
        }
        ?>
    </p>

    <?= Html::a('Más detalles', ['site/verproducto', 'idProducto' => $dato->idProducto], ['class' => 'botonDetalles']) ?>

</div>

views/site/clasificaciones.php
<?php

use yii\helpers\Html;

?>
<div class="row">
    <?php
    foreach ($clasificaciones as $clasificacion) {
    ?>
        <div class="col-6 mb-3">
            <div class="card bg-primary text-white">
                <div class="card-body carta">
                    <h3 class="card-title"><?= $clasificacion->nombre ?></h3>
                    <p><?= Html::a('Ver sección', ['site/productos', 'id' => $clasificacion->id], ['class' => 'btn btn-light']) ?></p>

                </div>
            </div>
        </div>
    <?php
    }
    ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Bienvenidos!</h1>

        <div>
            <?= Html::a('Hacer pedido', ['pedidos/create'], ['class' => 'btn btn-success']) ?>
        </div>
    </div>

    <div class="contenedor">

        <div>
            <?= Html::img(
                '@web/imgs/grocery.jpg',
                // ruta a la imagen 
                [
                    'class' => '',
                    'style' => '',  // o puedes poner 'width:500px'
                    'width' => '300px',
                    'height' => '300px',
                ],
            ) ?>
        </div>
        <div>
            <?= Html::img(
                '@web/imgs/frutas.jpg',
                // ruta a la imagen 
                [
                    'class' => '',
                    'style' => '',  // o puedes poner 'width:500px'
                    'width' => '300px',
                    'height' => '300px',
                ],
            ) ?>
        </div>
        <div>
            <?= Html::img(
                '@web/imgs/tomatos.jpg',
                // ruta a la imagen 
                [
                    'class' => '',
                    'style' => '',  // o puedes poner 'width:500px'
                    'width' => '300px',
                    'height' => '300px',
                ],
            ) ?>
        </div>
    </div>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/productos.php
<div class="contenedor">
    <div class="conjuntoProductos">
        <?php
        foreach ($datos as $dato) {
            echo $this->render('_productos', [
                'dato' => $dato,
            ]);
        }

        ?>
    </div>
</div>

views/site/verproducto.php
<?php

use yii\helpers\Html;
?>

<h2 style="text-align: center;margin:25px"> <?= $dato->nombre ?></h2>
<table class="tablaProducto">
    <tr>
        <td>Nombre producto</td>
        <td><?= $dato->nombre ?></td>
    </tr>
    <tr>
        <td>Descripción</td>
        <td><?= $dato->descripcion ?></td>
    </tr>
    <tr>
        <td>Foto</td>
        <td><?= Html::img("@web/imgs/productos/{$dato->foto}", ['width' => '400px', 'class' => 'img-fluid']) ?></td>
    </tr>
    <tr>
        <td>Precio</td>
        <td> <?= $dato->precio ?> €</td>
    </tr>
    <tr>
        <td>Sección</td>
        <td> <?= $dato->clasificacion0->nombre ?></td>
    </tr>

</table>